demo:
  craft:
    quickbooks-payroll:
      kafka:
        businessProfileValidationRequestTopic: "business-profile-validation-request"
        businessProfileValidationResponseTopic: "business-profile-validation-response"
    communication:
      kafka:
        bootstrapServers: 'localhost:9092'
        consumer:
          groupId: 'quickbooks-payroll'
spring:
  application:
    name: quickbooks-payroll
  main:
    banner-mode: off

logging:
  level:
    demo.craft.quickbooks.payroll: INFO
    org:
      springframework:
        web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 8083
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 15