spring:
  application:
    name: business-profile
  main:
    banner-mode: off
  datasource:
    name: business_profile
    url: jdbc:postgresql://localhost:5432/business_profile
    username: business_profile
    password: business_profile
    hikari:
      minimumIdle: 10
      maximumPoolSize: 25
      data-source-properties:
        #loggerLevel: TRACE
        logUnclosedConnections: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
    show-sql: false
  flyway:
    connectRetries: 20
    baselineOnMigrate: true
    baselineVersion: 0
    locations: classpath:db/migration

server:
  port: 8080
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 15