openapi: 3.0.0

info:
  title: User Profile
  description: Open API spec for User Profile
  version: 0.0.1

servers:
  - url: "http://localhost:8080"

paths:
  /user-profile/v1/business-profile:
    get:
      tags:
        - business-profile
      operationId: getBusinessProfile
      summary: Get business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Business profile of the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBusinessProfileResponse"

    post:
      tags:
        - business-profile
      operationId: createBusinessProfile
      summary: Create a new business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBusinessProfileRequest"
      responses:
        "200":
          description: Business profile created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateBusinessProfileResponse"

    put:
      tags:
        - business-profile
      operationId: updateBusinessProfile
      summary: Update business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBusinessProfileRequest"
      responses:
        "200":
          description: Business profile created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateBusinessProfileResponse"

  /user-profile/v1/business-profile/change-request/details:
    get:
      tags:
        - business-profile-change-request
      operationId: getBusinessProfileChangeRequestDetails
      summary: Get business profile change request details
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/requestId"
      responses:
        "200":
          description: Business profile change request details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBusinessProfileChangeRequestDetailsResponse"

  /user-profile/v1/business-profile/change-request/filter:
    get:
      tags:
        - business-profile-change-request
      operationId: getAllBusinessProfileChangeRequest
      summary: Get all business profile change request with filters
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/statusFilter"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
        - $ref: "#/components/parameters/sort"
      responses:
        "200":
          description: Business profile change requests with applied filters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAllBusinessProfileChangeRequestWithFiltersResponse"

components:
  parameters:
    userId:
      in: header
      name: x-user-id
      required: true
      schema:
        type: string

    requestId:
      in: query
      name: requestId
      required: true
      schema:
        type: string

    statusFilter:
      in: query
      name: status
      required: false
      schema:
        $ref: "#/components/schemas/ChangeRequestStatus"

    page:
      in: query
      name: page
      required: true
      schema:
        type: integer
        minimum: 0
        maximum: 10000

    pageSize:
      in: query
      name: size
      required: true
      schema:
        type: integer
        minimum: 1
        maximum: 50

    sort:
      in: query
      name: sort
      required: true
      schema:
        $ref: "#/components/schemas/SortOrder"

  schemas:
    SortOrder:
      type: string
      enum: [ ASC, DESC ]

    BusinessProfile:
      type: object
      required:
        - companyName
        - legalName
        - pan
        - ein
        - email
        - businessAddress
        - legalAddress
      properties:
        companyName:
          type: string
        legalName:
          type: string
        pan:
          type: string
        ein:
          type: string
        email:
          type: string
        website:
          type: string
        businessAddress:
          $ref: '#/components/schemas/Address'
        legalAddress:
          $ref: '#/components/schemas/Address'

    Address:
      type: object
      required:
        - line1
        - city
        - state
        - zip
        - country
      properties:
        line1:
          type: string
        line2:
          type: string
        line3:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
        country:
          type: string

    ChangeRequestStatus:
      type: string
      enum: [ IN_PROGRESS, ACCEPTED, REJECTED, FAILED ]

    ChangeRequestOperation:
      type: string
      enum: [ CREATE, UPDATE ]

    Product:
      type: string
      enum: [ QUICKBOOKS_ACCOUNTING, QUICKBOOKS_PAYROLL, QUICKBOOKS_PAYMENTS, TSHEETS ]

    BusinessProfileFieldName:
      type: string
      enum:
        - COMPANY_NAME
        - LEGAL_NAME
        - PAN
        - EIN
        - EMAIL
        - WEBSITE
        - BUSINESS_ADDRESS_LINE_1
        - BUSINESS_ADDRESS_LINE_2
        - BUSINESS_ADDRESS_LINE_3
        - BUSINESS_ADDRESS_CITY
        - BUSINESS_ADDRESS_STATE
        - BUSINESS_ADDRESS_ZIP
        - BUSINESS_ADDRESS_COUNTRY
        - LEGAL_ADDRESS_LINE_1
        - LEGAL_ADDRESS_LINE_2
        - LEGAL_ADDRESS_LINE_3
        - LEGAL_ADDRESS_CITY
        - LEGAL_ADDRESS_STATE
        - LEGAL_ADDRESS_ZIP
        - LEGAL_ADDRESS_COUNTRY

    GetBusinessProfileResponse:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"

    CreateBusinessProfileRequest:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"

    CreateBusinessProfileResponse:
      type: object
      required:
        - requestUuid
      properties:
        requestUuid:
          type: string

    UpdateBusinessProfileRequest:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"

    UpdateBusinessProfileResponse:
      type: object
      required:
        - requestUuid
      properties:
        requestUuid:
          type: string

    GetBusinessProfileChangeRequestDetailsResponse:
      type: object
      required:
        - changeRequestStatus
        - productStatuses
      properties:
        changeRequestStatus:
          $ref: "#/components/schemas/BusinessProfileChangeRequestStatus"
        productStatuses:
          type: array
          items:
            $ref: "#/components/schemas/ChangeRequestProductStatus"

    GetAllBusinessProfileChangeRequestWithFiltersResponse:
      type: object
      required:
        - changeRequestStatus
      properties:
        changeRequestStatuses:
          type: array
          items:
            $ref: "#/components/schemas/BusinessProfileChangeRequestStatus"

    BusinessProfileChangeRequestStatus:
      type: object
      required:
        - requestId
        - operation
        - status
      properties:
        requestId:
          type: string
        operation:
          $ref: "#/components/schemas/ChangeRequestOperation"
        status:
          $ref: '#/components/schemas/ChangeRequestStatus'

    ChangeRequestProductStatus:
      type: object
      required:
        - product
        - status
        - failureReasons
      properties:
        product:
          $ref: '#/components/schemas/Product'
        status:
          $ref: '#/components/schemas/ChangeRequestStatus'
        failureReasons:
          type: array
          items:
            $ref: "#/components/schemas/ProductFailureReason"

    ProductFailureReason:
      type: object
      required:
        - field
        - reason
      properties:
        field:
          $ref: '#/components/schemas/BusinessProfileFieldName'
        reason:
          type: string
