openapi: 3.0.0
info:
  title: User Profile
  description: Open API spec for User Profile
  version: 0.0.1
servers:
  - url: "http://localhost:8080"
paths:
  /user-profile/v1/business-profile:
    get:
      tags:
        - business-profile
      operationId: getBusinessProfile
      summary: Get business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Business profile of the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBusinessProfileResponse"
    post:
      tags:
        - business-profile
      operationId: createBusinessProfile
      summary: Create a new business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBusinessProfileRequest"
      responses:
        "200":
          description: Business profile created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateBusinessProfileResponse"
    patch:
      tags:
        - business-profile
      operationId: updateBusinessProfile
      summary: Update business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBusinessProfileRequest"
      responses:
        "200":
          description: Business profile created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateBusinessProfileResponse"
components:
  parameters:
    userId:
      in: header
      name: x-user-id
      required: true
      schema:
        type: string
  schemas:
    BusinessProfile:
      type: object
      required:
        - companyName
        - legalName
        - pan
        - ein
        - email
        - businessAddress
        - legalAddress
      properties:
        companyName:
          type: string
          example: Acme
        legalName:
          type: string
          example: Acme Corp
        pan:
          type: string
          example: XXXCX9999X
        ein:
          type: string
          example: 99-9999999
        email:
          type: string
          example: demo@acme.com
        website:
          type: string
          example: acme.com
        businessAddress:
          $ref: '#/components/schemas/Address'
        legalAddress:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      required:
        - line1
        - city
        - state
        - zip
        - country
      properties:
        line1:
          type: string
          example: House 101
        line2:
          type: string
          example: 1st Cross
        line3:
          type: string
          example: Rajiv Street
        city:
          type: string
          example: Bengaluru
        state:
          type: string
          example: Karnataka
        zip:
          type: string
          example: 560001
        country:
          type: string
          example: India
    ChangeRequestStatus:
      type: string
      enum: [ IN_PROGRESS, ACCEPTED, REJECTED ]
    GetBusinessProfileResponse:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"
    CreateBusinessProfileRequest:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"
    CreateBusinessProfileResponse:
      type: object
      required:
        - requestUuid
      properties:
        requestUuid:
          type: string
          example: af39e021-0acd-4451-8677-14ad95693b1b
    UpdateBusinessProfileRequest:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"
    UpdateBusinessProfileResponse:
      type: object
      required:
        - requestUuid
      properties:
        requestUuid:
          type: string
          example: af39e021-0acd-4451-8677-14ad95693b1b
