demo:
  craft:
    communication:
      kafka:
        bootstrapServers: "localhost:9092"
        consumer:
          groupId: "user-profile"
    user-profile:
      businessProfile:
        kafka:
          changeRequestTopicName: "business-profile-change-request"
          changeRequestProductTopicName: "business-profile-change-request-product"

spring:
  application:
    name: user-profile
  main:
    banner-mode: off
  datasource:
    name: user_profile
    url: jdbc:postgresql://localhost:5432/user_profile
    username: user_profile
    password: user_profile
    hikari:
      minimumIdle: 10
      maximumPoolSize: 25
      data-source-properties:
        #loggerLevel: TRACE
        logUnclosedConnections: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
    show-sql: false
  flyway:
    connectRetries: 20
    baselineOnMigrate: true
    baselineVersion: 0
    locations: classpath:db/migration

logging:
  level:
    demo.craft.user.profile: INFO
    org:
      springframework:
        web.filter.CommonsRequestLoggingFilter: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

server:
  port: 8080
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 15