package demo.craft.user.profile.common.domain.domain.enums

enum class FieldName {
    COMPANY_NAME,
    LEGAL_NAME,
    PAN,
    EIN,
    EMAIL,
    WEBSITE,
    BUSINESS_ADDRESS_LINE_1,
    BUSINESS_ADDRESS_LINE_2,
    BUSINESS_ADDRESS_LINE_3,
    BUSINESS_ADDRESS_CITY,
    BUSINESS_ADDRESS_STATE,
    BUSINESS_ADDRESS_ZIP,
    BUSINESS_ADDRESS_COUNTRY,
    LEGAL_ADDRESS_LINE_1,
    LEGAL_ADDRESS_LINE_2,
    LEGAL_ADDRESS_LINE_3,
    LEGAL_ADDRESS_CITY,
    LEGAL_ADDRESS_STATE,
    LEGAL_ADDRESS_ZIP,
    LEGAL_ADDRESS_COUNTRY
}